[package]
name = "rustic-ai-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
rustic-ai-core = { path = "../../rustic-ai-core" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
